# Generated by Django 3.2.16 on 2022-12-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.IntegerField(default='45'),
            preserve_default=False,
        ),
    ]
